apiVersion: v1
kind: ConfigMap
metadata:
  name: heat-ks-user-sh
data:
  ks-user.sh: |+
{{ tuple "bin/_ks-user.sh.tpl" . | include "template" | indent 4 }}
  ks-domain-user.sh: |+
{{ tuple "bin/_ks-domain-user.sh.tpl" . | include "template" | indent 4 }}
