# Copyright 2017 The Openstack-Helm Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
{{- $envAll := . }}
{{- $dependencies := .Values.dependencies.api }}
{{- $mounts_mistral_api := .Values.mounts.mistral_api.mistral_api }}
{{- $mounts_mistral_api_init := .Values.mounts.mistral_api.init_container }}

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mistral-api
spec:
  replicas: {{ .Values.replicas.api }}
  revisionHistoryLimit: {{ .Values.upgrades.revision_history }}
  strategy:
    type: {{ .Values.upgrades.pod_replacement_strategy }}
    {{ if eq .Values.upgrades.pod_replacement_strategy "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.upgrades.rolling_update.max_unavailable }}
      maxSurge: {{ .Values.upgrades.rolling_update.max_surge }}
    {{ end }}
  template:
    metadata:
      labels:
        app: mistral-api
      annotations:
        configmap-bin-hash: {{ tuple "configmap-bin.yaml" . | include "helm-toolkit.utils.hash" }}
        configmap-etc-hash: {{ tuple "configmap-etc.yaml" . | include "helm-toolkit.utils.hash" }}
        pod.beta.kubernetes.io/init-containers: '[
{{ tuple $envAll $dependencies $mounts_mistral_api_init | include "helm-toolkit.snippets.kubernetes_entrypoint_init_container" | indent 10 }}
        ]'
    spec:
      nodeSelector:
        {{ .Values.labels.node_selector_key }}: {{ .Values.labels.node_selector_value }}
      containers:
        - name: mistral-api
          image: {{ .Values.images.api }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
          {{- if .Values.resources.enabled }}
          resources:
            limits:
              cpu: {{ .Values.resources.api.limits.cpu | quote }}
              memory: {{ .Values.resources.api.limits.memory | quote }}
            requests:
              cpu: {{ .Values.resources.api.requests.cpu | quote }}
              memory: {{ .Values.resources.api.requests.memory | quote }}
          {{- end }}
          command:
            - bash
            - /tmp/mistral-api.sh
          ports:
            - name: {{ .Values.network.api.name }}
              containerPort: {{ .Values.conf.mistral.api.mistral.config.port }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.conf.mistral.api.mistral.config.port }}
          volumeMounts:
            - name: pod-etc-mistral
              mountPath: /etc/mistral
            - name: mistral-bin
              mountPath: /tmp/mistral-api.sh
              subPath: mistral-api.sh
              readOnly: true
            - name: mistral-etc
              mountPath: /etc/mistral/mistral.conf
              subPath: mistral.conf
              readOnly: true
            - name: mistral-etc
              mountPath: /etc/mistral/policy.json
              subPath: policy.json
              readOnly: true
{{ if $mounts_mistral_api.volumeMounts }}{{ toYaml $mounts_mistral_api.volumeMounts | indent 12 }}{{ end }}
      volumes:
        - name: pod-etc-mistral
          emptyDir: {}
        - name: mistral-bin
          configMap:
            name: mistral-bin
        - name: mistral-etc
          configMap:
            name: mistral-etc
{{ if $mounts_mistral_api.volumes }}{{ toYaml $mounts_mistral_api.volumes | indent 8 }}{{ end }}
