apiVersion: v1
kind: ConfigMap
metadata:
  name: glance-cephclientglancekeyring
data:
  ceph.client.{{ .Values.ceph.glance_user }}.keyring: |+
    [client.{{ .Values.ceph.glance_user }}]
        key = {{ .Values.ceph.glance_keyring }}
    
