apiVersion: batch/v1
kind: Job
metadata:
  name: glance-db-sync
spec:
  template:
    metadata:
      annotations:
{{  include "dep-check-init-cont-header" . | indent 8 }}
{{  include "dep-check-init-cont-footer" .Values.dependencies.db_sync | indent 8 }}
    spec:
      restartPolicy: OnFailure
      nodeSelector:
        {{ .Values.labels.node_selector_key }}: {{ .Values.labels.node_selector_value }}
      containers:
        - name: glance-db-sync
          image: {{ .Values.images.db_sync }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
          command:
            - bash
            - /tmp/db-sync.sh
          volumeMounts:
            - name: glanceapiconf
              mountPath: /etc/glance/glance-api.conf
              subPath: glance-api.conf
            - name: dbsyncsh
              mountPath: /tmp/db-sync.sh
              subPath: db-sync.sh
      volumes:
        - name: glanceapiconf
          configMap:
            name: glance-glanceapiconf
        - name: dbsyncsh
          configMap:
            name: glance-dbsyncsh
