# Copyright 2017 The Openstack-Helm Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- $envAll := . }}
{{- $dependencies := .Values.dependencies.registry }}
{{- $mounts_glance_registry := .Values.mounts.glance_registry.glance_registry }}
{{- $mounts_glance_registry_init := .Values.mounts.glance_registry.init_container }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: glance-registry
spec:
  replicas: {{ .Values.replicas.registry }}
  template:
    metadata:
      labels:
        app: glance-registry
      annotations:
        configmap-bin-hash: {{ tuple "configmap-bin.yaml" . | include "helm-toolkit.utils.hash" }}
        configmap-etc-hash: {{ tuple "configmap-etc.yaml" . | include "helm-toolkit.utils.hash" }}
        pod.beta.kubernetes.io/init-containers: '[
{{ tuple $envAll $dependencies $mounts_glance_registry_init | include "helm-toolkit.snippets.kubernetes_entrypoint_init_container" | indent 10 }}
        ]'
    spec:
      nodeSelector:
        {{ .Values.labels.node_selector_key }}: {{ .Values.labels.node_selector_value }}
      terminationGracePeriodSeconds: {{ .Values.termination_grace_period.registry.timeout | default "600" }}
      containers:
        - name: glance-registry
          image: {{ .Values.images.registry }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
          {{- if .Values.resources.enabled }}
          resources:
            limits:
              cpu: {{ .Values.resources.registry.limits.cpu | quote }}
              memory: {{ .Values.resources.registry.limits.memory | quote }}
            requests:
              cpu: {{ .Values.resources.registry.requests.cpu | quote }}
              memory: {{ .Values.resources.registry.requests.memory | quote }}
          {{- end }}
          command:
            - bash
            - /tmp/glance-registry.sh
          ports:
            - containerPort: {{ .Values.conf.glance_registry.default.glance.registry.bind_port }}
          lifecycle:
            preStop:
              exec:
                command:
                  - kill
                  - -TERM
                  - "1"
          readinessProbe:
            tcpSocket:
              port: {{ .Values.conf.glance_registry.default.glance.registry.bind_port }}
          volumeMounts:
            - name: etcglance
              mountPath: /etc/glance
            - name: glance-bin
              mountPath: /tmp/glance-registry.sh
              subPath: glance-registry.sh
              readOnly: true
            - name: glance-etc
              mountPath: /etc/glance/glance-registry.conf
              subPath: glance-registry.conf
              readOnly: true
            - name: glance-etc
              mountPath: /etc/glance/glance-registry-paste.ini
              subPath: glance-registry-paste.ini
              readOnly: true
            - name: glance-etc
              mountPath: /etc/glance/policy.json
              subPath: policy.json
              readOnly: true
{{ if $mounts_glance_registry.volumeMounts }}{{ toYaml $mounts_glance_registry.volumeMounts | indent 12 }}{{ end }}
      volumes:
        - name: etcglance
          emptyDir: {}
        - name: glance-bin
          configMap:
            name: glance-bin
        - name: glance-etc
          configMap:
            name: glance-etc
{{ if $mounts_glance_registry.volumes }}{{ toYaml $mounts_glance_registry.volumes | indent 8 }}{{ end }}
