apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: glance-api
spec:
{{- if .Values.development.enabled }}
  replicas: 1
{{- else }}
  replicas: {{ .Values.replicas.api }}
{{- end }}
  revisionHistoryLimit: {{ .Values.upgrades.revision_history }}
  strategy:
    type: {{ .Values.upgrades.pod_replacement_strategy }}
    {{ if eq .Values.upgrades.pod_replacement_strategy "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.upgrades.rolling_update.max_unavailable }}
      maxSurge: {{ .Values.upgrades.rolling_update.max_surge }}
    {{ end }}
  template:
    metadata:
      labels:
        app: glance-api
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "init",
            "image": "quay.io/stackanetes/kubernetes-entrypoint:v0.1.0",
            "imagePullPolicy": "{{ .Values.images.pull_policy }}",
            "env": [
              {
                "name": "NAMESPACE",
                "value": "{{ .Release.Namespace }}"
              },
              {
                "name": "DEPENDENCY_SERVICE",
                "value": "{{  include "joinListWithColon" .Values.dependencies.api.service }}"
              },
              {
                "name": "DEPENDENCY_JOBS",
                "value": "{{  include "joinListWithColon" .Values.dependencies.api.jobs }}"
              },
              {
                "name": "COMMAND",
                "value": "echo done"
              }
            ]
          }
        ]'
    spec:
      nodeSelector:
        {{ .Values.labels.node_selector_key }}: {{ .Values.labels.node_selector_value }}

      containers:
        - name: glance-api
          image: {{ .Values.images.api }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
          command:
          - glance-api
          ports:
            - containerPort: {{ .Values.network.port.api }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.network.port.api }}
          volumeMounts:
            - name: glanceapiconf
              mountPath: /etc/glance/glance-api.conf
              subPath: glance-api.conf
            - name: glanceapipaste
              mountPath: /etc/glance/glance-api-paste.ini
              subPath: glance-api-paste.ini
            - name: etcglance
              mountPath: /etc/glance
            - name: glancepolicy
              mountPath: /etc/glance/policy.json
              subPath: policy.json
{{- if .Values.development.enabled }}
            - name: glance-data
              mountPath: /var/lib/glance/images
{{- else }}
            - name: cephconf
              mountPath: /etc/ceph/ceph.conf
              subPath: ceph.conf
            - name: cephclientglancekeyring
              mountPath: /etc/ceph/ceph.client.{{ .Values.ceph.glance_user }}.keyring
              subPath: ceph.client.{{ .Values.ceph.glance_user }}.keyring
{{- end }}
      volumes:
        - name: glanceapiconf
          configMap:
            name: glance-etc
        - name: glanceapipaste
          configMap:
            name: glance-etc
{{- if .Values.development.enabled }}
        - name: glance-data
          hostPath:
            path: {{ .Values.development.storage_path }}
{{- else }}
        - name: cephconf
          configMap:
            name: glance-etc
        - name: cephclientglancekeyring
          configMap:
            name: glance-etc
{{- end }}
        - name: etcglance
          emptyDir: {}
        - name: glancepolicy
          configMap:
            name: glance-etc
