apiVersion: batch/v1
kind: Job
metadata:
  name: glance-init
spec:
  template:
    metadata:
      annotations:
      {{  include "init-containers-header" . }}
      {{  include "init-containers-footer" .Values.dependencies.init }}
    spec:
      restartPolicy: OnFailure
      nodeSelector:
        {{ .Values.labels.node_selector_key }}: {{ .Values.labels.node_selector_value }}
      containers:
        - name: glance-init
          image: {{ .Values.images.init }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
          env:
          - name: ANSIBLE_LIBRARY
            value: /usr/share/ansible/
          command:
            - bash
            - /tmp/init.sh
          volumeMounts:
            - name: initsh
              mountPath: /tmp/init.sh
              subPath: init.sh
      volumes:
        - name: initsh
          configMap:
            name: glance-initsh
