apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: glance-registry
spec:
  minAvailable: {{ .Values.pod_disruption_budget.registry.min_available }}
  selector:
    matchLabels:
      app: glance-registry