apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: glance-registry
spec:
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: glance-registry
      annotations:
      {{  include "init-containers-header" . }}
      {{  include "init-containers-footer" .Values.dependencies.registry }}
    spec:
      nodeSelector:
        {{ .Values.labels.node_selector_key }}: {{ .Values.labels.node_selector_value }}
      containers:
        - name: glance-registry
          image: {{ .Values.images.registry }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
          command:
          - glance-registry
          ports:
            - containerPort: {{ .Values.network.port.registry }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.network.port.registry }}
          volumeMounts:
            - name: glanceregistryconf
              mountPath: /etc/glance/glance-registry.conf
              subPath: glance-registry.conf
      volumes:
        - name: glanceregistryconf
          configMap:
            name: glance-glanceregistryconf
