apiVersion: v1
kind: ConfigMap
metadata:
  name: glance-startsh
data:
  start.sh: |+
    #!/bin/bash
    set -ex

    cp `find / -not -path "/etc/*" -name glance-api-paste.ini` /etc/glance/

    glance-api
