apiVersion: batch/v1
kind: Job
metadata:
  name: heat-db-sync
spec:
  template:
    metadata:
      annotations:
      {{  include "init-containers-header" . }}
      {{  include "init-containers-footer" .Values.dependencies.db_sync }}
    spec:
      restartPolicy: OnFailure
      nodeSelector:
        {{ .Values.labels.node_selector_key }}: {{ .Values.labels.node_selector_value }}
      containers:
        - name: heat-db-sync
          image: {{ .Values.images.db_sync }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
          command:
            - heat-manage
          args:
            - --config-dir
            - /etc/heat/conf
            - db_sync
          volumeMounts:
            - name: pod-etc-heat
              mountPath: /etc/heat
            - name: heatconf
              mountPath: /etc/heat/conf/heat.conf
              subPath: heat.conf
              readOnly: true
      volumes:
        - name: pod-etc-heat
          emptyDir: {}
        - name: heatconf
          configMap:
            name: heat-etc
