apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: heat-cfn
spec:
  minAvailable: {{ .Values.pod_disruption_budget.cfn.min_available }}
  selector:
    matchLabels:
      app: heat-cfn