apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: heat-cloudwatch
spec:
  minAvailable: {{ .Values.pod_disruption_budget.cloudwatch.min_available }}
  selector:
    matchLabels:
      app: heat-cloudwatch