apiVersion: v1
kind: Secret
metadata:
  name: heat-env-keystone-user
type: Opaque
data:
  OS_AUTH_URL: |
{{ .Values.keystone.auth_url  | b64enc | indent 4 }}
  OS_REGION_NAME: |
{{ .Values.keystone.heat_region_name  | b64enc | indent 4 }}
  OS_PROJECT_DOMAIN_NAME: |
{{ .Values.keystone.heat_project_domain  | b64enc | indent 4 }}
  OS_PROJECT_NAME: |
{{ .Values.keystone.heat_project_name  | b64enc | indent 4 }}
  OS_USER_DOMAIN_NAME: |
{{ .Values.keystone.heat_user_domain  | b64enc | indent 4 }}
  OS_USERNAME: |
{{ .Values.keystone.heat_user  | b64enc | indent 4 }}
  OS_PASSWORD: |
{{ .Values.keystone.heat_password  | b64enc | indent 4 }}
