apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: heat-engine
spec:
  serviceName: heat-engine
  replicas: {{ .Values.replicas.engine }}
  template:
    metadata:
      labels:
        app: heat-engine
      annotations:
      {{  include "dep-check-init-cont-header" . }}
      {{  include "dep-check-init-cont-footer" .Values.dependencies.engine }}
    spec:
      nodeSelector:
        {{ .Values.labels.node_selector_key }}: {{ .Values.labels.node_selector_value }}
      containers:
        - name: heat-engine
          image: {{ .Values.images.engine }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
          command:
            - heat-engine
            - --config-dir
            - /etc/heat/conf
          volumeMounts:
            - name: pod-etc-heat
              mountPath: /etc/heat
            - name: pod-var-cache-heat
              mountPath: /var/cache/heat
            - name: heatconf
              mountPath: /etc/heat/conf/heat.conf
              subPath: heat.conf
              readOnly: true
      volumes:
        - name: pod-etc-heat
          emptyDir: {}
        - name: pod-var-cache-heat
          emptyDir: {}
        - name: heatconf
          configMap:
            name: heat-etc
