apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: keystone-api
spec:
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: keystone-api
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "init",
            "image": "quay.io/stackanetes/kubernetes-entrypoint:v0.1.0",
            "env": [
              {
                "name": "NAMESPACE",
                "value": "{{ .Release.Namespace }}"
              },
              {
                "name": "DEPENDENCY_SERVICE",
                "value": "mariadb,rabbitmq"
              },
              {
                "name": "DEPENDENCY_JOBS",
                "value": "mariadb-seed"
              },
              {
                "name": "DEPENDENCY_CONFIG",
                "value": "/etc/apache2/conf-enabled/wsgi-keystone.conf"
              },
              {
                "name": "COMMAND",
                "value": "echo done"
              }              
            ]
          }
        ]'
    spec:
      nodeSelector:
        {{ .Values.labels.node_selector_key }}: {{ .Values.labels.node_selector_value }}
      containers:
        - name: keystone-api
          image: {{ .Values.images.api }}
          command:
            - bash
            - /tmp/start.sh
          ports:
            - containerPort: {{ .Values.network.port.public }}
            - containerPort: {{ .Values.network.port.admin }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.network.port.public }}
          volumeMounts:
            - name: keystoneconf
              mountPath: /etc/keystone/keystone.conf
              subPath: keystone.conf
            - name: wsgikeystone
              mountPath: /configmaps/wsgi-keystone.conf
            - name: mpmeventconf
              mountPath: /etc/apache2/mods-available/mpm_event.conf
              subPath: mpm_event.conf
            - name: startsh
              mountPath: /tmp/start.sh
              subPath: start.sh
      volumes:
        - name: keystoneconf
          configMap:
            name: keystone-keystoneconf
        - name: wsgikeystone
          configMap:
            name: keystone-wsgikeystone
        - name: mpmeventconf
          configMap:
            name: keystone-mpmeventconf
            # https://github.com/kubernetes/kubernetes/issues/23722
            items:
            - key: mpm-event.conf
              path: mpm_event.conf
        - name: startsh
          configMap:
            name: keystone-startsh
