apiVersion: batch/v1
kind: Job
metadata:
  name: keystone-init
spec:
  template:
    metadata:
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "init",
            "image": "quay.io/stackanetes/kubernetes-entrypoint:v0.1.0",
            "env": [
              {
                "name": "NAMESPACE",
                "value": "{{ .Release.Namespace }}"
              },
              {
                "name": "DEPENDENCY_SERVICE",
                "value": "{{  include "joinListWithColon" .Values.dependencies.init.service }}"
              },
              {
                "name": "DEPENDENCY_JOBS",
                "value": "{{  include "joinListWithColon" .Values.dependencies.init.jobs }}"
              },
              {
                "name": "COMMAND",
                "value": "echo done"
              }
            ]
          }
        ]'
    spec:
      restartPolicy: OnFailure
      containers:
        - name: keystone-init
          image: {{ .Values.images.init }}
          imagePullPolicy: Always
          command:
            - bash
            - /tmp/init.sh
          volumeMounts:
            - name: initsh
              mountPath: /tmp/init.sh
              subPath: init.sh
      volumes:
        - name: initsh
          configMap:
            name: keystone-initsh
