apiVersion: batch/v1
kind: Job
metadata:
  name: keystone-db-sync
spec:
  template:
    metadata:
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "init",
            "image": "{{ .Values.images.entrypoint }}",
            "env": [
              {
                "name": "NAMESPACE",
                "value": "{{ .Release.Namespace }}"
              },            
              {
                "name": "DEPENDENCY_SERVICE",
                "value": "mariadb"
              },
              {
                "name": "DEPENDENCY_JOBS",
                "value": "mariadb-seed,keystone-init"
              },
              {
                "name": "COMMAND",
                "value": "echo done"
              }
            ]
          }
        ]'
    spec:
      restartPolicy: OnFailure
      containers:
        - name: keystone-db-sync
          image: {{ .Values.images.db_sync }}
          imagePullPolicy: Always
          command:
            - bash
            - /tmp/db-sync.sh
          volumeMounts:
            - name: keystoneconf
              mountPath: /etc/keystone/keystone.conf
              subPath: keystone.conf
            - name: keystone-bin
              mountPath: /tmp/db-sync.sh
              subPath: db-sync.sh
      volumes:
        - name: keystoneconf
          configMap:
            name: keystone-etc
        - name: keystone-bin
          configMap:
            name: keystone-bin
