apiVersion: batch/v1
kind: Job
metadata:
  name: keystone-db-sync
spec:
  template:
    metadata:
      annotations:
      {{  include "init-containers-header" . }}
      {{  include "init-containers-footer" .Values.dependencies.db_sync }}
    spec:
      restartPolicy: OnFailure
      nodeSelector:
        {{ .Values.labels.node_selector_key }}: {{ .Values.labels.node_selector_value }}
      containers:
        - name: keystone-db-sync
          image: {{ .Values.images.db_sync }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
          command:
            - bash
            - /tmp/db-sync.sh
          volumeMounts:
            - name: keystoneconf
              mountPath: /etc/keystone/keystone.conf
              subPath: keystone.conf
            - name: keystone-bin
              mountPath: /tmp/db-sync.sh
              subPath: db-sync.sh
      volumes:
        - name: keystoneconf
          configMap:
            name: keystone-etc
        - name: keystone-bin
          configMap:
            name: keystone-bin
