{{- $envAll := . }}
{{- $dependecies := .Values.dependencies.init }}
apiVersion: batch/v1
kind: Job
metadata:
  name: keystone-init
spec:
  template:
    metadata:
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
{{ tuple $envAll $dependecies | include "dep-check-init-cont" | indent 10 }}
        ]'
    spec:
      restartPolicy: OnFailure
      nodeSelector:
        {{ .Values.labels.node_selector_key }}: {{ .Values.labels.node_selector_value }}
      containers:
        - name: keystone-init
          image: {{ .Values.images.init }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
          command:
            - bash
            - /tmp/init.sh
          volumeMounts:
            - name: keystone-bin
              mountPath: /tmp/init.sh
              subPath: init.sh
      volumes:
        - name: keystone-bin
          configMap:
            name: keystone-bin
