apiVersion: v1
kind: ConfigMap
metadata:
  name: keystone-keystoneconf
data:
  keystone.conf: |+
    [DEFAULT]
    debug = {{ .Values.global.misc.debug }}
    use_syslog = False
    use_stderr = True
    workers = {{ .Values.global.misc.workers }}

    [database]
    connection = mysql+pymysql://{{ .Values.global.database.keystone_user }}:{{ .Values.global.database.keystone_password }}@{{ .Values.global.database.address }}/{{ .Values.global.database.keystone_database_name }}
    max_retries = -1

    [memcache]
    servers = {{ .Values.global.memcached.address }}

    [cache]
    backend = dogpile.cache.memcached
    memcache_servers = {{.Values.global.memcached.address}}
    config_prefix = cache.keystone
    distributed_lock = True
    enabled = True

