apiVersion: v1
kind: Service
metadata:
  name: keystone-api
spec:
  ports:
  - name: keystone-api-public
    port: {{ .Values.global.network.port.public }}
  - name: keystone-api-admin
    port: {{ .Values.global.network.port.admin }}
  selector:
    app: keystone-api
