# Copyright 2017 The Openstack-Helm Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
{{- $envAll := . }}
{{- $dependencies := .Values.dependencies.api }}
{{- $mounts_cinder_api := .Values.mounts.cinder_api.cinder_api }}
{{- $mounts_cinder_api_init := .Values.mounts.cinder_api.init_container }}

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cinder-api
spec:
  replicas: {{ .Values.replicas.api }}
  revisionHistoryLimit: {{ .Values.upgrades.revision_history }}
  strategy:
    type: {{ .Values.upgrades.pod_replacement_strategy }}
    {{ if eq .Values.upgrades.pod_replacement_strategy "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.upgrades.rolling_update.max_unavailable }}
      maxSurge: {{ .Values.upgrades.rolling_update.max_surge }}
    {{ end }}
  template:
    metadata:
      labels:
        app: cinder-api
      annotations:
        configmap-bin-hash: {{ tuple "configmap-bin.yaml" . | include "helm-toolkit.utils.hash" }}
        configmap-etc-hash: {{ tuple "configmap-etc.yaml" . | include "helm-toolkit.utils.hash" }}
    spec:
      nodeSelector:
        {{ .Values.labels.node_selector_key }}: {{ .Values.labels.node_selector_value }}
      terminationGracePeriodSeconds: {{ .Values.termination_grace_period.api.timeout | default "30" }}
      initContainers:
{{ tuple $envAll $dependencies $mounts_cinder_api_init | include "helm-toolkit.snippets.kubernetes_entrypoint_init_container" | indent 8 }}
      containers:
        - name: cinder-api
          image: {{ .Values.images.api }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
          {{- if .Values.resources.enabled }}
          resources:
            requests:
              memory: {{ .Values.resources.cinder_api.requests.memory | quote }}
              cpu: {{ .Values.resources.cinder_api.requests.cpu | quote }}
            limits:
              memory: {{ .Values.resources.cinder_api.limits.memory | quote }}
              cpu: {{ .Values.resources.cinder_api.limits.cpu | quote }}
          {{- end }}
          command:
            - bash
            - /tmp/cinder-api.sh
            - start
          lifecycle:
            preStop:
              exec:
                command:
                  - bash
                  - /tmp/cinder-api.sh
                  - stop
          ports:
            - name: c-api
              containerPort: {{ .Values.conf.cinder.default.cinder.osapi_volume_listen_port }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.conf.cinder.default.cinder.osapi_volume_listen_port }}
          volumeMounts:
            - name: pod-var-cache-cinder
              mountPath: /var/cache/cinder
            - name: cinder-bin
              mountPath: /tmp/cinder-api.sh
              subPath: cinder-api.sh
              readOnly: true
            - name: cinder-etc
              mountPath: /etc/cinder/cinder.conf
              subPath: cinder.conf
              readOnly: true
            - name: cinder-etc
              mountPath: /etc/cinder/api-paste.ini
              subPath: api-paste.ini
              readOnly: true
            - name: cinder-etc
              mountPath: /etc/cinder/policy.json
              subPath: policy.json
              readOnly: true
{{ if $mounts_cinder_api.volumeMounts }}{{ toYaml $mounts_cinder_api.volumeMounts | indent 12 }}{{ end }}
      volumes:
        - name: pod-var-cache-cinder
          emptyDir: {}
        - name: cinder-bin
          configMap:
            name: cinder-bin
        - name: cinder-etc
          configMap:
            name: cinder-etc
{{ if $mounts_cinder_api.volumes }}{{ toYaml $mounts_cinder_api.volumes | indent 8 }}{{ end }}
