# Copyright 2017 The Openstack-Helm Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- $envAll := . }}
{{- $dependencies := .Values.dependencies.init }}
apiVersion: batch/v1
kind: Job
metadata:
  name: senlin-db-init
spec:
  template:
    spec:
      restartPolicy: OnFailure
      nodeSelector:
        {{ .Values.labels.node_selector_key }}: {{ .Values.labels.node_selector_value }}
      initContainers:
{{ tuple $envAll $dependencies "[]" | include "helm-toolkit.snippets.kubernetes_entrypoint_init_container" | indent 8 }}
      containers:
        - name: senlin-db-init
          image: {{ .Values.images.db_init | quote }}
          imagePullPolicy: {{ .Values.images.pull_policy | quote }}
          {{- if .Values.resources.enabled }}
          resources:
            requests:
              memory: {{ .Values.resources.senlin_db_init.requests.memory | quote }}
              cpu: {{ .Values.resources.senlin_db_init.requests.cpu | quote }}
            limits:
              memory: {{ .Values.resources.senlin_db_init.limits.memory | quote }}
              cpu: {{ .Values.resources.senlin_db_init.limits.cpu | quote }}
          {{- end }}
          env:
            - name: ROOT_DB_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: senlin-db-root
                  key: DB_CONNECTION
            - name: OPENSTACK_CONFIG_FILE
              value: /etc/senlin/senlin.conf
            - name: OPENSTACK_CONFIG_DB_SECTION
              value: database
            - name: OPENSTACK_CONFIG_DB_KEY
              value: connection
          command:
            - python
            - /tmp/db-init.py
          volumeMounts:
            - name: senlin-bin
              mountPath: /tmp/db-init.py
              subPath: db-init.py
              readOnly: true
            - name: etcsenlin
              mountPath: /etc/senlin
            - name: senlin-etc
              mountPath: /etc/senlin/senlin.conf
              subPath: senlin.conf
              readOnly: true
      volumes:
        - name: etcsenlin
          emptyDir: {}
        - name: senlin-etc
          configMap:
            name: senlin-etc
        - name: senlin-bin
          configMap:
            name: senlin-bin
