apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: senlin-api
spec:
  minAvailable: {{ .Values.pod_disruption_budget.api.min_available }}
  selector:
    matchLabels:
      app: senlin-api