apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: heat-engine
spec:
  serviceName: heat-engine
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: heat-engine
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "init",
            "image": {{ .Values.images.dep_check | quote }},
            "imagePullPolicy": {{ .Values.images.pull_policy | quote }},
            "env": [
              {
                "name": "NAMESPACE",
                "value": "{{ .Release.Namespace }}"
              },
              {
                "name": "DEPENDENCY_SERVICE",
                "value": "{{  include "joinListWithColon" .Values.dependencies.engine.service }}"
              },
              {
                "name": "DEPENDENCY_JOBS",
                "value": "{{  include "joinListWithColon" .Values.dependencies.engine.jobs }}"
              },
              {
                "name": "COMMAND",
                "value": "echo done"
              }
            ]
          }
        ]'
    spec:
      nodeSelector:
        {{ .Values.labels.node_selector_key }}: {{ .Values.labels.node_selector_value }}
      containers:
        - name: heat-engine
          image: {{ .Values.images.engine }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
          command:
          - bash
          - /tmp/start.sh
          volumeMounts:
            - name: heat-engine-sh
              mountPath: /tmp/start.sh
              subPath: start.sh
              readOnly: true
            - name: heat-conf-engine
              mountPath: /etc/heat/conf/heat-engine.conf
              subPath: heat-engine.conf
              readOnly: true
{{ include "heat_config_volume_mounts" . | indent 12 }}
      volumes:
        - name: heat-engine-sh
          configMap:
            name: heat-engine-sh
        - name: heat-conf-engine
          configMap:
            name: heat-conf-engine
{{ include "heat_config_volumes" . | indent 8 }}
