dependencies:
  # - name: memcached
  #   repository: http://localhost:8879/charts
  #   version: 0.1.0
  # - name: rabbitmq
  #   repository: http://localhost:8879/charts
  #   version: 0.1.0
  # - name: keystone
  #   repository: http://localhost:8879/charts
  #   version: 0.1.0
  - name: utils
    repository: http://localhost:8879/charts
    version: 0.1.0
