# Default values for ceph.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
#
# alanmeadows(NOTE): this is merely a sample of the potential
# tunables available - parameterizing more of the elements
# in the manifests is a work in progress

images:
  daemon: quay.io/attcomdev/ceph-daemon:latest

labels:
  node_selector_key: ceph-storage
  node_selector_value: enabled

network:
  port: 
    mon: 6789
    rgw_ingress: 80
    rgw_target: 8088

storage:
  osd_directory: /var/lib/aic-helm/ceph/osd
  var_directory: /var/lib/aic-helm/ceph/ceph

# Setting this to false will assume you will
# setup and orchestrate your own secrets and 
# configmaps outside of this helm chart
# 
# The list below is in the format of
#
#   configMapName:
#      elementKeyName
#
#   ceph.conf: 
#      ceph.conf
#      ceph.client.admin.keyring
#      ceph.client.admin.keyring
#   ceph.mon.keyring: 
#      ceph.mon.keyring
#   ceph-bootstrap-rgw-keyring:
#      ceph.keyring
#      ceph.rgw.keyring
#   ceph-bootstrap-mds-keyring:
#      ceph.keyring
#      ceph.mds.keyring
#   ceph-bootstrap-osd-keyring:
#      ceph.keyring
#      ceph.osd.keyring
#   ceph-client-key:
#      ceph-client-key
secrets:
  use_common_secrets: true

# if you change provision_storage_class to false
# it is presumed you manage your own storage
# class definition externally
storageclass:
  provision_storage_class: true
  name: general
  monitors: null 
  pool: rbd
  admin_id: admin
  admin_secret_name: pvc-ceph-conf-combined-storageclass
  admin_secret_namespace: null
  user_id: admin
  user_secret_name: pvc-ceph-client-key
