# Default values for keystone.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

image_ceph_daemon: quay.io/attcomdev/ceph-daemon:latest
node_label: storage
ceph_mon_port: 6789
ceph_rgw_ingress_port: 80
ceph_rgw_target_port: 8088
