apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: ceph-mon
spec:
  minAvailable: {{ .Values.pod_disruption_budget.mon.min_available }}
  selector:
    matchLabels:
      app: ceph
      daemon: mon