---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{.Release.Namespace}}
  name: "ceph-conf-combined"
  # This declares the resource to be a hook. By convention, we also name the
  # file "pre-install-XXX.yaml", but Helm itself doesn't care about file names.
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  ceph.conf: |
{{ include "secrets/ceph.conf.b64"  .| indent 4 }}
  ceph.client.admin.keyring: |
{{ include "secrets/ceph.client.admin.keyring.b64" . | indent 4 }}
  ceph.mon.keyring: |
{{ include "secrets/ceph.mon.keyring.b64" . | indent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{.Release.Namespace}}
  name: "ceph-bootstrap-rgw-keyring"
  # This declares the resource to be a hook. By convention, we also name the
  # file "pre-install-XXX.yaml", but Helm itself doesn't care about file names.
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  ceph.keyring: |
{{ include "secrets/ceph.rgw.keyring.b64" . | indent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{.Release.Namespace}}
  name: "ceph-bootstrap-mds-keyring"
  # This declares the resource to be a hook. By convention, we also name the
  # file "pre-install-XXX.yaml", but Helm itself doesn't care about file names.
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  ceph.keyring: |
{{ include "secrets/ceph.mds.keyring.b64"  . | indent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{.Release.Namespace}}
  name: "ceph-bootstrap-osd-keyring"
  # This declares the resource to be a hook. By convention, we also name the
  # file "pre-install-XXX.yaml", but Helm itself doesn't care about file names.
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  ceph.keyring: |
{{ include "secrets/ceph.osd.keyring.b64"  . | indent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{.Release.Namespace}}
  name: "ceph-client-key"
  # This declares the resource to be a hook. By convention, we also name the
  # file "pre-install-XXX.yaml", but Helm itself doesn't care about file names.
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  ceph-client-key: {{ include "secrets/ceph-client-key.b64"  . | quote }}  
