{{- if .Values.secrets.use_common_secrets -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: "ceph-conf-combined"
type: Opaque
data:
  ceph.conf: |
{{ include "secrets/ceph.conf" . | b64enc | indent 4 }}
  ceph.client.admin.keyring: |
{{ include "secrets/ceph.client.admin.keyring" . | b64enc | indent 4 }}
  ceph.mon.keyring: |
{{ include "secrets/ceph.mon.keyring" . | b64enc | indent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "ceph-bootstrap-rgw-keyring"
type: Opaque
data:
  ceph.keyring: |
{{ include "secrets/ceph.rgw.keyring" . | b64enc | indent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "ceph-bootstrap-mds-keyring"
type: Opaque
data:
  ceph.keyring: |
{{ include "secrets/ceph.mds.keyring" . | b64enc | indent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "ceph-bootstrap-osd-keyring"
type: Opaque
data:
  ceph.keyring: |
{{ include "secrets/ceph.osd.keyring" . | b64enc | indent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "ceph-client-key"
type: Opaque
data:
  ceph-client-key: |
{{ include "secrets/ceph-client-key" . | b64enc | indent 4 }}
{{- end -}}
