---
kind: Service
apiVersion: v1
metadata:
  name: ceph-mon
  labels:
    app: ceph
    daemon: mon
spec:
  ports:
  - port: {{ .Values.ceph_mon_port }}
    protocol: TCP
    targetPort: {{ .Values.ceph_mon_port }}
  selector:
    app: ceph
    daemon: mon
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: ceph-rgw
  labels:
    app: ceph
    daemon: rgw
spec:
  ports:
  - port: {{ .Values.ceph_rgw_ingress_port }}
    protocol: TCP
    targetPort: {{ .Values.ceph_rgw_target_port }}
  selector:
    app: ceph
    daemon: rgw
  type: LoadBalancer
