---
kind: Service
apiVersion: v1
metadata:
  name: ceph-mon
  labels:
    app: ceph
    daemon: mon
spec:
  ports:
  - port: {{ .Values.network.port.mon }}
    protocol: TCP
    targetPort: {{ .Values.network.port.mon }}
  selector:
    app: ceph
    daemon: mon
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: ceph-rgw
  labels:
    app: ceph
    daemon: rgw
spec:
  ports:
  - port: {{ .Values.network.port.rgw_ingress }}
    protocol: TCP
    targetPort: {{ .Values.network.port.rgw_target }}
  selector:
    app: ceph
    daemon: rgw
  type: LoadBalancer
