# note that these secrets are handled by the common chart, not the ceph
# chart, as we likely want them "everywhere"
---
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
    name: {{ .Values.storageclass.name }}
provisioner: kubernetes.io/rbd
parameters:
    monitors: {{ .Values.storageclass.monitors | default "ceph-mon.ceph:6789" }}
    adminId: {{ .Values.storageclass.admin_id }}
    adminSecretName: {{ .Values.storageclass.admin_secret_name }}
    # forcing namespace due to issue with default pipeline of "{{ .Release.Namespace }}" }}
    # during helm lint
    adminSecretNamespace: {{ .Values.storageclass.admin_secret_namespace | default "ceph" }}
    pool: {{ .Values.storageclass.pool }}
    userId: {{ .Values.storageclass.user_id }}
    userSecretName: {{ .Values.storageclass.user_secret_name }}
