# note that these secrets are handled by the common chart, not the ceph
# chart, as we likely want them "everywhere"
---
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
    name: general
provisioner: kubernetes.io/rbd
parameters:
    monitors: ceph-mon.{{.Release.Namespace}}:6789
    adminId: admin
    adminSecretName: pvc-ceph-conf-combined-storageclass
    adminSecretNamespace: {{.Release.Namespace}}
    pool: rbd
    userId: admin
    userSecretName: pvc-ceph-client-key