apiVersion: v1
kind: ConfigMap
metadata:
  name: maas-region-bin
data:
  start.sh: |
{{ tuple "bin/_start.sh.tpl" . | include "template" | indent 4 }}
  maas-region-controller.postinst: |
{{ tuple "bin/_maas-region-controller.postinst.tpl" . | include "template" | indent 4 }}
