apiVersion: v1
kind: ConfigMap
metadata:
  name: maas-region-var
data:
  maas-region-controller.postinst: |
{{ tuple "var/_maas-region-controller.postinst.tpl" . | include "template" | indent 4 }}
  secret: |
{{ tuple "var/_secret.tpl" . | include "template" | indent 4 }}

