apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: maas-region
spec:
  template:
    metadata:
      labels:
        app: maas-region
    spec:
      nodeSelector:
        {{ .Values.labels.node_selector_key }}: {{ .Values.labels.node_selector_value }}
      containers:
      - name: maas-region
        image: {{ .Values.images.maas_region }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.network.port.region_container }}
        securityContext:
          privileged: true
