apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: maas-region
spec:
  template:
    metadata:
      labels:
        app: maas-region
    spec:
      containers:
      - name: maas-region
        image: {{ .Values.image_maas_region }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.maas_region_container_port }}
        securityContext:
          privileged: true
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: maas-rack
spec:
  template:
    metadata:
      labels:
        app: maas-rack-controller
    spec:
      hostNetwork: true
      containers:
      - name: maas-rack
        image: {{ .Values.image_maas_rack }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.maas_rack_container_port }}
        securityContext:
          privileged: true
