apiVersion: v1
kind: Service
metadata:
  name: maas-region-ui
  labels:
    app: maas-region-ui
spec:
  ports:
  - port: {{ .Values.network.port.service_gui }}
    targetPort: {{ .Values.network.port.service_gui_target }}
    protocol: TCP
    name: gui
  - port: {{ .Values.network.port.service_proxy }}
    targetPort: {{ .Values.network.port.service_proxy_target }}
    protocol: TCP
    name: proxy
  selector:
    app: maas-region
