apiVersion: v1
kind: Service
metadata:
  name: maas-region-ui
  labels:
    app: maas-region-ui
spec:
  ports:
  - port: {{ .Values.service_gui_port }}
    targetPort: {{ .Values.service_gui_target_port }}
    protocol: TCP
    name: gui
  - port: {{ .Values.service_proxy_port }}
    targetPort: {{ .Values.service_proxy_target_port }}
    protocol: TCP
    name: proxy
  selector:
    app: maas-region
