---
apiVersion: v1
kind: Secret
metadata:
  name: "pvc-ceph-conf-combined-storageclass"
type: kubernetes.io/rbd
data: 
  key: |
{{ include "secrets/ceph-client-key" . | indent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "pvc-ceph-client-key"
type: kubernetes.io/rbd
data:
  key: |
{{ include "secrets/ceph-client-key" . | indent 4 }}
