apiVersion: v1
kind: Secret
metadata:
  name: heat-conf-stack-domain
type: Opaque
data:
  heat-stack-domain.conf: |
{{ tuple "contents/_heat-stack-domain.conf.tpl" . | include "template"  | b64enc | indent 4 }}
  OS_REGION_NAME: |
{{ .Values.keystone.heat_stack_region_name  | b64enc | indent 4 }}
  OS_DOMAIN_NAME: |
{{ .Values.keystone.heat_stack_domain  | b64enc | indent 4 }}
  OS_USERNAME: |
{{ .Values.keystone.heat_stack_user  | b64enc | indent 4 }}
  OS_PASSWORD: |
{{ .Values.keystone.heat_stack_password  | b64enc | indent 4 }}
