apiVersion: v1
kind: Secret
metadata:
  name: heat-conf-trustee
type: Opaque
data:
  heat-trustee.conf: |
{{ tuple "contents/_heat-trustee.conf.tpl" . | include "template" | b64enc | indent 4 }}
  OS_AUTH_URL: |
{{ .Values.keystone.auth_url  | b64enc | indent 4 }}
  OS_REGION_NAME: |
{{ .Values.keystone.heat_trustee_region_name  | b64enc | indent 4 }}
  OS_PROJECT_DOMAIN_NAME: |
{{ .Values.keystone.heat_trustee_project_domain  | b64enc | indent 4 }}
  OS_PROJECT_NAME: |
{{ .Values.keystone.heat_trustee_project_name  | b64enc | indent 4 }}
  OS_USER_DOMAIN_NAME: |
{{ .Values.keystone.heat_trustee_user_domain  | b64enc | indent 4 }}
  OS_USERNAME: |
{{ .Values.keystone.heat_trustee_user  | b64enc | indent 4 }}
  OS_PASSWORD: |
{{ .Values.keystone.heat_trustee_password  | b64enc | indent 4 }}
