# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
replicas:
  api: 1

labels:
  node_selector_key: openstack-control-plane
  node_selector_value: enabled

images:
  dep_check: docker.io/kolla/ubuntu-source-kubernetes-entrypoint:4.0.0
  db_init: docker.io/kolla/ubuntu-source-barbican-api:3.0.3
  db_sync: docker.io/kolla/ubuntu-source-barbican-api:3.0.3
  ks_user: docker.io/kolla/ubuntu-source-kolla-toolbox:3.0.3
  ks_service: docker.io/kolla/ubuntu-source-kolla-toolbox:3.0.3
  ks_endpoints: docker.io/kolla/ubuntu-source-kolla-toolbox:3.0.3
  api: docker.io/kolla/ubuntu-source-barbican-api:3.0.3
  pull_policy: "IfNotPresent"

upgrades:
  revision_history: 3
  pod_replacement_strategy: RollingUpdate
  rolling_update:
    max_unavailable: 1
    max_surge: 3

network:
  api:
    name: "barbican-api"
    proto: "http"
    node_port:
      enabled: false
      port: 39486

keystone:
  admin_user: "admin"
  admin_user_domain: "default"
  admin_password: "password"
  admin_project_name: "admin"
  admin_project_domain: "default"
  admin_region_name: "RegionOne"

  barbican_user: "barbican"
  barbican_user_domain: "default"
  barbican_user_role: "admin"
  barbican_password: "password"
  barbican_project_name: "service"
  barbican_project_domain: "default"
  barbican_region_name: "RegionOne"

dependencies:
  db_init:
    jobs:
    - mariadb-seed
    service:
    - mariadb
  db_sync:
    jobs:
    - barbican-db-init
    service:
    - mariadb
  ks_user:
    service:
    - keystone-api
  ks_service:
    service:
    - keystone-api
  ks_endpoints:
    jobs:
    - barbican-ks-service
    service:
    - keystone-api
  api:
    jobs:
    - barbican-db-sync
    - barbican-ks-user
    - barbican-ks-endpoints
    service:
    - keystone-api
    - mariadb

conf:
  paste:
    override:
    append:
  policy:
    override:
    append:
  audit_map:
    override:
    append:
  barbican:
    override:
    append:
    keystone_authtoken:
      keystonemiddleware:
        auth_token:
          auth_type: password
          auth_version: v3
          region_name: RegionOne
          project_domain_name: default
          project_name: service
          user_domain_name: default
          username: barbican
          password: password
    database:
      oslo:
        db:
          max_retries: -1
    barbican_api:
      barbican:
        config:
          bind_port: 9311

endpoints:
  identity:
    name: keystone
    hosts:
      default: keystone-api
    path: /v3
    scheme: http
    port:
      admin: 35357
      api: 5000
  key-manager:
    name: barbican
    hosts:
      default: barbican-api
    path: /v1
    scheme: http
    port:
      api: 9311
  oslo_db:
    auth:
      admin:
        username: root
        password: password
      user:
        username: barbican
        password: password
    hosts:
      default: mariadb
    path: /barbican
    scheme: mysql+pymysql
    port:
      mysql: 3306
  oslo_messaging:
    auth:
      admin:
        username: admin
        password: password
      user:
        username: rabbitmq
        password: password
    hosts:
      default: rabbitmq
    path: /
    scheme: rabbit
    port:
      amqp: 5672
  oslo_cache:
    hosts:
      default: memcache
    port:
      memcache: 11211

resources:
  enabled: false
  db_init:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "1024Mi"
      cpu: "2000m"
  db_sync:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "1024Mi"
      cpu: "2000m"
  ks_endpoints:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "1024Mi"
      cpu: "2000m"
  ks_service:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "1024Mi"
      cpu: "2000m"
  ks_user:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "1024Mi"
      cpu: "2000m"
  api:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "1024Mi"
      cpu: "2000m"

mounts:
  barbican_api:
    init_container: null
    barbican_api:
