apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: nova-api-osapi
spec:
  minAvailable: {{ .Values.pod_disruption_budget.osapi.min_available }}
  selector:
    matchLabels:
      app: nova-api-osapi