apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: nova-api-metadata
spec:
  minAvailable: {{ .Values.pod_disruption_budget.metadata.min_available }}
  selector:
    matchLabels:
      app: nova-api-metadata