apiVersion: v1
kind: Service
metadata:
  # alanmeadows(TODO): refactor to nova-osapi
  # which requires updating other charts
  # dependencies
  name: nova-api
spec:
  ports:
  - name: nova-osapi
    port: {{ .Values.network.port.osapi }}
  selector:
    app: nova-osapi
