apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: neutron-openvswitch
spec:
  template:
    metadata:
      labels:
        app: neutron-openvswitch
    spec:
      nodeSelector:
        {{ .Values.labels.ovs.node_selector_key }}: {{ .Values.labels.ovs.node_selector_value }}    
      securityContext:
        runAsUser: 0
      dnsPolicy: ClusterFirst
      hostNetwork: true
      containers:
        - name: neutron-openvswitch-agent
          image: {{ .Values.images.neutron_openvswitch_agent }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
          securityContext:
            privileged: true
          # ensures this container can can see a br-int
          # bridge before its marked as ready
          readinessProbe:
            exec:
              command:
                - bash
                - -c
                - 'ovs-vsctl list-br | grep -q br-int'
          env:
            - name: INTERFACE_NAME
              value: {{ .Values.network.interface.openvswitch | default .Values.network.interface.default }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: COMMAND
              value: "bash /tmp/neutron-openvswitch-agent.sh"
            - name: DEPENDENCY_JOBS
              value: "{{  include "joinListWithColon" .Values.dependencies.openvswitchagent.jobs }}"
            - name: DEPENDENCY_SERVICE
              value: "{{  include "joinListWithColon" .Values.dependencies.openvswitchagent.service }}"
            - name: DEPENDENCY_CONTAINER
              value: "{{  include "joinListWithColon" .Values.dependencies.openvswitchagent.container }}"
          volumeMounts:
            - name: neutronopenvswitchagentsh
              mountPath: /tmp/neutron-openvswitch-agent.sh
              subPath: neutron-openvswitch-agent.sh
            - name: neutronconf
              mountPath: /etc/neutron/neutron.conf
              subPath: neutron.conf
            - name: ml2confini
              mountPath: /etc/neutron/plugins/ml2/ml2-conf.ini
              subPath: ml2-conf.ini
            - name: libmodules
              mountPath: /lib/modules
              readOnly: true
            - name: run
              mountPath: /run
            - mountPath: /etc/resolv.conf
              name: resolvconf
              subPath: resolv.conf
        - name: openvswitch-db-server
          image: {{ .Values.images.openvswitch_db_server }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
          securityContext:
            privileged: true
          env:
            - name: INTERFACE_NAME
              value: {{ .Values.network.interface.openvswitch | default .Values.network.interface.default }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: COMMAND
              value: "bash /tmp/openvswitch-db-server.sh"
          volumeMounts:
            - name: openvswitchdbserversh
              mountPath: /tmp/openvswitch-db-server.sh
              subPath: openvswitch-db-server.sh
            - mountPath: /etc/resolv.conf
              name: resolvconf
              subPath: resolv.conf
            - name: varlibopenvswitch
              mountPath: /var/lib/openvswitch/
            - name: run
              mountPath: /run

        - name: openvswitch-vswitchd
          image: {{ .Values.images.openvswitch_vswitchd }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
          securityContext:
            privileged: true
          # ensures this container can speak to the ovs database
          # successfully before its marked as ready
          readinessProbe:
            exec:
              command:
                - /usr/bin/ovs-vsctl
                - show
          env:
            - name: INTERFACE_NAME
              value: {{ .Values.network.interface.openvswitch | default .Values.network.interface.default }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: COMMAND
              value: "bash /tmp/openvswitch-vswitchd.sh"
            - name: DEPENDENCY_CONTAINER
              value: "openvswitch-db-server"
          volumeMounts:
            - name: openvswitchvswitchdsh
              mountPath: /tmp/openvswitch-vswitchd.sh
              subPath: openvswitch-vswitchd.sh
            - name: openvswitchensureconfiguredsh
              mountPath: /tmp/openvswitch-ensure-configured.sh
              subPath: openvswitch-ensure-configured.sh
            - name: libmodules
              mountPath: /lib/modules
              readOnly: true
            - name: run
              mountPath: /run
      volumes:
        - name: openvswitchdbserversh
          configMap:
            name: neutron-bin
        - name: openvswitchvswitchdsh
          configMap:
            name: neutron-bin
        - name: openvswitchensureconfiguredsh
          configMap:
            name: neutron-bin
        - name: varlibopenvswitch
          emptyDir: {}
        - name: neutronopenvswitchagentsh
          configMap:
            name: neutron-bin
        - name: neutronconf
          configMap:
            name: neutron-etc
        - name: ml2confini
          configMap:
            name: neutron-etc
        - name: resolvconf
          configMap:
            name: neutron-etc
        - name: libmodules
          hostPath:
            path: /lib/modules
        - name: run
          hostPath:
            path: /run