apiVersion: batch/v1
kind: Job
metadata:
  name: neutron-init
spec:
  template:
    spec:
      restartPolicy: OnFailure
      nodeSelector:
        {{ .Values.labels.node_selector_key }}: {{ .Values.labels.node_selector_value }}
      containers:
        - name: neutron-init
          image: {{ .Values.images.init }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
          env:
            - name: INTERFACE_NAME
              value: "eth0"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: COMMAND
              value: "bash /tmp/init.sh"
            - name: DEPENDENCY_JOBS
              value: "{{  include "joinListWithColon" .Values.dependencies.init.jobs }}"
            - name: DEPENDENCY_SERVICE
              value: "{{  include "joinListWithColon" .Values.dependencies.init.service }}"
          volumeMounts:
            - name: initsh
              mountPath: /tmp/init.sh
              subPath: init.sh
      volumes:
        - name: initsh
          configMap:
            name: neutron-bin