apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: neutron-server
spec:
  minAvailable: {{ .Values.pod_disruption_budget.server.min_available }}
  selector:
    matchLabels:
      app: neutron-server