# Copyright 2017 The Openstack-Helm Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- $envAll := . }}
{{- $dependencies := .Values.dependencies.db_sync }}
apiVersion: batch/v1
kind: Job
metadata:
  name: magnum-db-sync
spec:
  template:
    metadata:
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
{{ tuple $envAll $dependencies "[]" | include "helm-toolkit.snippets.kubernetes_entrypoint_init_container" | indent 10 }}
        ]'
    spec:
      restartPolicy: OnFailure
      nodeSelector:
        {{ .Values.labels.node_selector_key }}: {{ .Values.labels.node_selector_value }}
      containers:
        - name: magnum-db-sync
          image: {{ .Values.images.db_sync }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
          {{- if .Values.resources.enabled }}
          resources:
            requests:
              memory: {{ .Values.resources.magnum_db_sync.requests.memory | quote }}
              cpu: {{ .Values.resources.magnum_db_sync.requests.cpu | quote }}
            limits:
              memory: {{ .Values.resources.magnum_db_sync.limits.memory | quote }}
              cpu: {{ .Values.resources.magnum_db_sync.limits.cpu | quote }}
          {{- end }}
          command:
            - bash
            - /tmp/db-sync.sh
          volumeMounts:
            - name: magnum-bin
              mountPath: /tmp/db-sync.sh
              subPath: db-sync.sh
              readOnly: true
            - name: etcmagnum
              mountPath: /etc/magnum
            - name: magnum-etc
              mountPath: /etc/magnum/magnum.conf
              subPath: magnum.conf
              readOnly: true
      volumes:
        - name: etcmagnum
          emptyDir: {}
        - name: magnum-etc
          configMap:
            name: magnum-etc
        - name: magnum-bin
          configMap:
            name: magnum-bin
