# Default values for mariadb.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

replicas: "3" # this must be quoted to deal with atoi

images:
  mariadb: quay.io/stackanetes/stackanetes-mariadb:newton

volume:
  size: 20Gi

labels:
  node_selector_key: openstack-control-plane
  node_selector_value: enabled

network:
  port:
    wsrep: 4567 
    mariadb: 3306 
  dns:
    kubernetes_domain: cluster.local
  ip_address: "{{ .IP }}"
  
database:
  root_password: password
  cluster_name: mariadb
  node_name: master
