deployment:
  image: quay.io/stackanetes/stackanetes-mariadb:newton
  control_node_label: openstack-control-plane
network:
  port:
    wsrep: 4567 
    mariadb: 3306 
  dns:
    kubernetes_domain: cluster.local
  ip_address: "{{ .IP }}"
database:
  root_password: password
  cluster_name: mariadb
  node_name: master
