# Copyright 2017 The Openstack-Helm Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Default values for keystone.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value


replicas:
  api: 1
  engine: 1

labels:
  node_selector_key: openstack-control-plane
  node_selector_value: enabled

images:
  db_init: docker.io/kolla/ubuntu-source-senlin-api:3.0.3
  db_sync: docker.io/kolla/ubuntu-source-senlin-api:3.0.3
  ks_user: docker.io/kolla/ubuntu-source-kolla-toolbox:3.0.3
  ks_service: docker.io/kolla/ubuntu-source-kolla-toolbox:3.0.3
  ks_endpoints: docker.io/kolla/ubuntu-source-kolla-toolbox:3.0.3
  api: docker.io/kolla/ubuntu-source-senlin-api:3.0.3
  engine: docker.io/kolla/ubuntu-source-senlin-engine:3.0.3
  dep_check: docker.io/kolla/ubuntu-source-kubernetes-entrypoint:4.0.0
  pull_policy: "IfNotPresent"

upgrades:
  revision_history: 3
  pod_replacement_strategy: RollingUpdate
  rolling_update:
    max_unavailable: 1
    max_surge: 3

keystone_secrets:
  admin: "senlin-env-keystone-admin"
  user: "senlin-env-keystone-user"

keystone:
  admin_user: "admin"
  admin_user_domain: "default"
  admin_password: "password"
  admin_project_name: "admin"
  admin_project_domain: "default"
  admin_region_name: "RegionOne"

  senlin_user_role: "admin"


conf:
  paste:
    override:
    append:
  policy:
    override:
    append:
  senlin:
    override:
    append:
    keystone_authtoken:
      keystonemiddleware:
        auth_token:
          auth_type: password
          auth_version: v3
          region_name: RegionOne
          project_domain_name: default
          project_name: service
          user_domain_name: default
          username: senlin
          password: password
    senlin_api:
      senlin:
        config:
          bind_port: 8778

network:
  api:
    name: "senlin-api"
    proto: "http"
    node_port:
      enabled: false
      port: 30778

dependencies:
  db_init:
    service:
    - mariadb
  db_sync:
    jobs:
    - senlin-db-init
    service:
    - mariadb
  ks_user:
    service:
    - keystone-api
  ks_service:
    service:
    - keystone-api
  ks_endpoints:
    jobs:
    - senlin-ks-service
    service:
    - keystone-api
  api:
    jobs:
    - senlin-db-sync
    - senlin-ks-user
    - senlin-ks-endpoints
    service:
    - keystone-api
    - mariadb
  engine:
    jobs:
    - senlin-db-sync
    - senlin-ks-user
    - senlin-ks-endpoints
    service:
    - keystone-api
    - mariadb

# typically overriden by environmental
# values, but should include all endpoints
# required by this chart
endpoints:
  identity:
    name: keystone
    hosts:
      default: keystone-api
    path: /v3
    scheme: 'http'
    port:
      admin: 35357
      api: 5000
  clustering:
    name: senlin
    hosts:
      default: senlin-api
    path: null
    scheme: 'http'
    port:
      api: 8778
  oslo_db:
    auth:
      admin:
        username: root
        password: password
      user:
        username: senlin
        password: password
    hosts:
      default: mariadb
    path: /senlin
    scheme: mysql+pymysql
    port:
      mysql: 3306
  oslo_cache:
    hosts:
      default: memcache
    port:
      memcache: 11211
  oslo_messaging:
    auth:
      admin:
        username: admin
        password: password
      user:
        username: rabbitmq
        password: password
    hosts:
      default: rabbitmq
    path: /
    scheme: rabbit
    port:
      amqp: 5672

resources:
  enabled: false
  senlin_api:
    requests:
      memory: "124Mi"
      cpu: "100m"
    limits:
      memory: "1024Mi"
      cpu: "2000m"
  senlin_db_init:
    requests:
      memory: "124Mi"
      cpu: "100m"
    limits:
      memory: "1024Mi"
      cpu: "2000m"
  senlin_db_sync:
    requests:
      memory: "124Mi"
      cpu: "100m"
    limits:
      memory: "1024Mi"
      cpu: "2000m"
  senlin_ks_endpoints:
    requests:
      memory: "124Mi"
      cpu: "100m"
    limits:
      memory: "1024Mi"
      cpu: "2000m"
  senlin_ks_service:
    requests:
      memory: "124Mi"
      cpu: "100m"
    limits:
      memory: "1024Mi"
      cpu: "2000m"
  senlin_ks_user:
    requests:
      memory: "124Mi"
      cpu: "100m"
    limits:
      memory: "1024Mi"
      cpu: "2000m"
  senlin_engine:
    requests:
      memory: "124Mi"
      cpu: "100m"
    limits:
      memory: "1024Mi"
      cpu: "2000m"

mounts:
  senlin_api:
    init_container: null
    senlin_api:
  senlin_engine:
    init_container: null
    senlin_engine:
