# Default values for openstack.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

global:
  # (alanmeadows) NOTE: these two items are not easily changeable yet
  region: cluster
  tld: local
  images:
    ceph_rbd_job: quay.io/attcomdev/ceph-daemon:latest

  labels:
    control_node_label: openstack-control-plane
