# Default values for openstack.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

mariadb:
  images:
    mariadb: quay.io/stackanetes/stackanetes-mariadb:newton
  volume:
    size: 20Gi
  labels:
    control_node_label: openstack-control-plane

  images:
    ceph_rbd_job: quay.io/attcomdev/ceph-daemon:latest

  labels:
    control_node_label: openstack-control-plane
