apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heat-api
spec:
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: heat-api
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "init",
            "image": {{ .Values.images.dep_check | quote }},
            "imagePullPolicy": {{ .Values.images.pull_policy | quote }},
            "env": [
              {
                "name": "NAMESPACE",
                "value": "{{ .Release.Namespace }}"
              },
              {
                "name": "DEPENDENCY_SERVICE",
                "value": "{{  include "joinListWithColon" .Values.dependencies.api.service }}"
              },
              {
                "name": "DEPENDENCY_JOBS",
                "value": "{{  include "joinListWithColon" .Values.dependencies.api.jobs }}"
              },
              {
                "name": "COMMAND",
                "value": "echo done"
              }
            ]
          }
        ]'
    spec:
      nodeSelector:
        {{ .Values.labels.node_selector_key }}: {{ .Values.labels.node_selector_value }}
      containers:
        - name: heat-api
          image: {{ .Values.images.api }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
          command:
          - bash
          - /tmp/start.sh
          ports:
            - containerPort: {{ .Values.service.api.port }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.api.port }}
          volumeMounts:
            - name: heat-api-sh
              mountPath: /tmp/start.sh
              subPath: start.sh
              readOnly: true
            - name: heat-ini-api-paste
              mountPath: /etc/heat/api-paste.ini
              subPath: api-paste.ini
              readOnly: true
            - name: heat-conf-api
              mountPath: /etc/heat/conf/heat-api.conf
              subPath: heat-api.conf
              readOnly: true
{{ include "heat_config_volume_mounts" . | indent 12 }}
      volumes:
        - name: heat-api-sh
          configMap:
            name: heat-api-sh
        - name: heat-ini-api-paste
          configMap:
            name: heat-ini-api-paste
        - name: heat-conf-api
          configMap:
            name: heat-conf-api
{{ include "heat_config_volumes" . | indent 8 }}
