apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-bin
data:
  start.sh: |
{{ tuple "bin/_start.sh.tpl" . | include "template" | indent 4 }}  
  peer-finder.py: |
{{ tuple "bin/_peer-finder.py.tpl" . | include "template" | indent 4 }}
  readiness.py: |
{{ tuple "bin/_readiness.py.tpl" . | include "template" | indent 4 }}  
  bootstrap-db.sh: |
{{ tuple "bin/_bootstrap-db.sh.tpl" . | include "template" | indent 4 }}
  seed.sh: |
{{ tuple "bin/_seed.sh.tpl" . | include "template" | indent 4 }}  
