apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ tuple "oslo_db" "internal" . | include "helm-toolkit.endpoints.hostname_short_endpoint_lookup" }}
spec:
  minAvailable: {{ .Values.pod_disruption_budget.mariadb.min_available }}
  selector:
    matchLabels:
      app: mariadb
