apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.service_name }}
spec:
  minAvailable: {{ .Values.pod_disruption_budget.mariadb.min_available }}
  selector:
    matchLabels:
      app: {{ .Values.service_name }}