apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-wsrep
data:
  wsrep.cnf: |+
    [mysqld]
    wsrep_cluster_name="{{ .Values.database.cluster_name }}"
    wsrep_provider=/usr/lib/galera/libgalera_smm.so
    wsrep_provider_options="gcache.size=512M"
    wsrep_slave_threads=12
    wsrep_sst_auth=root:{{ .Values.database.root_password }}
    wsrep_sst_method=xtrabackup-v2
    wsrep_node_name={{ .Values.database.node_name }}
    wsrep_node_address={{ .Values.network.ip_address }}:{{ .Values.network.port.wsrep }}
