kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: rabbitmq
spec:
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      nodeSelector:
        {{ .Values.labels.node_selector_key }}: {{ .Values.labels.node_selector_value }}
      volumes:
        - name: rabbitmq-emptydir
          emptyDir: {}
        - name: rabbitmq-bin
          configMap:
            name: rabbitmq-bin
      containers:
        - name: rabbitmq
          image: {{ .Values.images.rabbitmq }}
          command:
            - bash
            - /tmp/start_rabbitmq.sh
          livenessProbe:
            tcpSocket:
              port: {{.Values.network.port.public}}
            initialDelaySeconds: 60
            timeoutSeconds: 5
          ports:
            - name: rabbitmq
              containerPort: {{.Values.network.port.public}}
            - name: management
              containerPort: {{.Values.network.port.management}}
          volumeMounts:
            - name: rabbitmq-emptydir
              mountPath: /var/lib/rabbitmq
            - name: rabbitmq-bin
              mountPath: /tmp/start_rabbitmq.sh
              subPath: start_rabbitmq.sh
