dependencies:
  - name: common
    repository: http://localhost:8879/charts
    version: 0.1.0
dependencies:
  - name: mariadb
    repository: http://localhost:8879/charts
    version: 0.1.0    
dependencies:
  - name: rabbitmq
    repository: http://localhost:8879/charts
    version: 0.1.0    
dependencies:
  - name: memcached
    repository: http://localhost:8879/charts
    version: 0.1.0
