# Default values for keystone.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

replicas: 1

labels:
  node_selector_key: openstack-control-plane
  node_selector_value: enabled

images:
  db_sync: quay.io/stackanetes/stackanetes-keystone-api:newton
  api: quay.io/stackanetes/stackanetes-keystone-api:newton 
  init: quay.io/stackanetes/stackanetes-kolla-toolbox:newton

keystone:
  version: v2.0
  scheme: http
  admin_region_name: RegionOne 
  admin_user: admin
  admin_password: password
  admin_project_name: admin

network:
  port:
    admin: 35357
    public: 5000
  ip_address: "{{ .IP }}"

database:
  port: 3306
  root_user: root
  root_password: password
  keystone_database_name: keystone
  keystone_password: password
  keystone_user: keystone

misc:
  workers: 8
  debug: false

dependencies:
  api:
    jobs: 
    - mariadb-seed
    - keystone-db-sync
    service:
    - mariadb
  db_sync:
    jobs:
    - keystone-init
    - mariadb-seed
    service:
    - mariadb
  init:
    jobs:
    - mariadb-seed
    service:
    - mariadb
