global:
  deployment:
    replicas: 1
    control_node_label: openstack-control-plane
    image:
      db_sync: quay.io/stackanetes/stackanetes-keystone-api:newton
      api: quay.io/stackanetes/stackanetes-keystone-api:newton 
      init: quay.io/stackanetes/stackanetes-kolla-toolbox:newton
  network:
    port:
      admin: 35357
      public: 5000
    ip_address: "{{ .IP }}"
  database:
    address: mariadb
    port: 3306
    root_user: root
    root_password: password
    keystone_database_name: keystone
    keystone_password: password
    keystone_user: keystone
  keystone:
    admin_region_name: RegionOne 
    admin_user: admin
    admin_password: password
    admin_project_name: admin
  memcached:
    address: memcached
  misc:
    workers: 8
    debug: false
