apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: horizon
spec:
  minAvailable: {{ .Values.pod_disruption_budget.horizon.min_available }}
  selector:
    matchLabels:
      app: horizon