apiVersion: v1
kind: Service
metadata:
  name: horizon
spec:
  ports:
    {{ if .Values.network.enable_node_port }}
    - nodePort: {{ .Values.network.node_port }}
      port: {{ .Values.network.port }}
      protocol: TCP
      targetPort: {{ .Values.network.port }}
    {{ else }}
    - port: {{ .Values.network.port }}
      protocol: TCP
      targetPort: {{ .Values.network.port }}
    {{ end }}
  selector:
    app: horizon
  {{ if .Values.network.enable_node_port }}
  type: NodePort
  {{ end }}
