apiVersion: batch/v1
kind: Job
metadata:
  name: cinder-ks-endpoints
spec:
  template:
    metadata:
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "init",
            "image": {{ .Values.images.dep_check | quote }},
            "imagePullPolicy": {{ .Values.images.pull_policy | quote }},
            "env": [
              {
                "name": "NAMESPACE",
                "value": "{{ .Release.Namespace }}"
              },
              {
                "name": "DEPENDENCY_SERVICE",
                "value": "{{  include "joinListWithColon" .Values.dependencies.ks_endpoints.service }}"
              },
              {
                "name": "DEPENDENCY_JOBS",
                "value": "{{  include "joinListWithColon" .Values.dependencies.ks_endpoints.jobs }}"
              },
              {
                "name": "COMMAND",
                "value": "echo done"
              }
            ]
          }
        ]'
    spec:
      restartPolicy: OnFailure
      containers:
        - name: cinder-ks-endpoints-v1-admin
{{ include "container_ks_endpoint" . | indent 10 }}
            - name: OS_SERVICE_INTERFACE
              value: admin
            - name: OS_SERVICE_NAME
              value: cinder
            - name: OS_SERVICE_TYPE
              value: volume
            - name: OS_SERVICE_ENDPOINT
              value: {{ .Values.service.api.proto }}://{{ .Values.service.api.name }}:{{ .Values.service.api.port }}/v1/%(tenant_id)s
        - name: cinder-ks-endpoints-v1-internal
{{ include "container_ks_endpoint" . | indent 10 }}
            - name: OS_SERVICE_INTERFACE
              value: internal
            - name: OS_SERVICE_NAME
              value: cinder
            - name: OS_SERVICE_TYPE
              value: volume
            - name: OS_SERVICE_ENDPOINT
              value: {{ .Values.service.api.proto }}://{{ .Values.service.api.name }}:{{ .Values.service.api.port }}/v1/%(tenant_id)s
        - name: cinder-ks-endpoints-v1-public
{{ include "container_ks_endpoint" . | indent 10 }}
            - name: OS_SERVICE_INTERFACE
              value: public
            - name: OS_SERVICE_NAME
              value: cinder
            - name: OS_SERVICE_TYPE
              value: volume
            - name: OS_SERVICE_ENDPOINT
              value: {{ .Values.service.api.proto }}://{{ .Values.service.api.name }}:{{ .Values.service.api.port }}/v1/%(tenant_id)s
        - name: cinder-ks-endpoints-v2-admin
{{ include "container_ks_endpoint" . | indent 10 }}
            - name: OS_SERVICE_INTERFACE
              value: admin
            - name: OS_SERVICE_NAME
              value: cinder
            - name: OS_SERVICE_TYPE
              value: volumev2
            - name: OS_SERVICE_ENDPOINT
              value: {{ .Values.service.api.proto }}://{{ .Values.service.api.name }}:{{ .Values.service.api.port }}/v2/%(tenant_id)s
        - name: cinder-ks-endpoints-v2-internal
{{ include "container_ks_endpoint" . | indent 10 }}
            - name: OS_SERVICE_INTERFACE
              value: internal
            - name: OS_SERVICE_NAME
              value: cinder
            - name: OS_SERVICE_TYPE
              value: volumev2
            - name: OS_SERVICE_ENDPOINT
              value: {{ .Values.service.api.proto }}://{{ .Values.service.api.name }}:{{ .Values.service.api.port }}/v2/%(tenant_id)s
        - name: cinder-ks-endpoints-v2-public
{{ include "container_ks_endpoint" . | indent 10 }}
            - name: OS_SERVICE_INTERFACE
              value: public
            - name: OS_SERVICE_NAME
              value: cinder
            - name: OS_SERVICE_TYPE
              value: volumev2
            - name: OS_SERVICE_ENDPOINT
              value: {{ .Values.service.api.proto }}://{{ .Values.service.api.name }}:{{ .Values.service.api.port }}/v2/%(tenant_id)s
        - name: cinder-ks-endpoints-v3-admin
{{ include "container_ks_endpoint" . | indent 10 }}
            - name: OS_SERVICE_INTERFACE
              value: admin
            - name: OS_SERVICE_NAME
              value: cinder
            - name: OS_SERVICE_TYPE
              value: volumev3
            - name: OS_SERVICE_ENDPOINT
              value: {{ .Values.service.api.proto }}://{{ .Values.service.api.name }}:{{ .Values.service.api.port }}/v3/%(tenant_id)s
        - name: cinder-ks-endpoints-v3-internal
{{ include "container_ks_endpoint" . | indent 10 }}
            - name: OS_SERVICE_INTERFACE
              value: internal
            - name: OS_SERVICE_NAME
              value: cinder
            - name: OS_SERVICE_TYPE
              value: volumev3
            - name: OS_SERVICE_ENDPOINT
              value: {{ .Values.service.api.proto }}://{{ .Values.service.api.name }}:{{ .Values.service.api.port }}/v3/%(tenant_id)s
        - name: cinder-ks-endpoints-v3-public
{{ include "container_ks_endpoint" . | indent 10 }}
            - name: OS_SERVICE_INTERFACE
              value: public
            - name: OS_SERVICE_NAME
              value: cinder
            - name: OS_SERVICE_TYPE
              value: volumev3
            - name: OS_SERVICE_ENDPOINT
              value: {{ .Values.service.api.proto }}://{{ .Values.service.api.name }}:{{ .Values.service.api.port }}/v3/%(tenant_id)s
      volumes:
        - name: ks-endpoints-sh
          configMap:
            name: cinder-ks-endpoints-sh
